{% set name = "userinput" %}
{% set version = "1.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/userinput-{{ version }}.tar.gz
  sha256: 26432f745b052d48eac60a836dda470f79a51b1f4b936f76020250b93238c75f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - validators
    - validate_version_code
    - validate_email
    - environments_utils
    - ipython
    - ipy
    - jaro-winkler
    - numpy

test:
  imports:
    - userinput
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LucaCappelletti94/userinput
  summary: Simple python package to handle cli user input.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
